### ISSUE TITLE
options.btnConsultar.button is not a function

### ISSUE THREAD

**Issue by gpassarelli** [hewerthomn/jquery-consultar-cep#7]
Pessoal, estou tendo problemas na minha aplicação quando insiro um CEP inválido, ele da um erro de:
`options.btnConsultar.button is not a function` na linha [#87](https://github.com/hewerthomn/jquery-consultar-cep/blob/master/jquery.consultar-cep.js#L87) e estou usando a opção de blur.

Algum ideia do que possa ser isso?

Na página de exemplo funciona normal.

**Comment by gpassarelli** [comment]
Bom, acho que achei o problema, é que não estou carregando o JS do Twitter Bootstrap.
É preciso o JS do Bootstrap?

**Comment by hewerthomn** [comment]
Verdade, o método .button() é do Bootstrap para exibir a mensagem de carregando no botão

**Comment by gpassarelli** [comment]
Mas faz sentido ter esse button mesmo para quando o trigger é "blur"?

Em seg, 11 de jan de 2016 20:39, Everton Inocencio <notifications@github.com>
escreveu:

**Comment by hewerthomn** [comment]
Não faz sentido, acho que nem deveria depender do Bootstrap...

**Comment by rands0n** [comment]
Vamos deixar aberta pra corrigir no futuro @gpassarelli. Muito obrigado pela issue.
